### PR TITLE
Update types.ts

### PR DESCRIPTION
**Pull request by Swoorup**
* Make internally updated properties optional. 
* Add built-in Spline and Candle overlay types.

### CODE REVIEW

**Review by C451 — COMMENTED** [review]
Why `"Spline" | "Candles" | string;` instead of `string`? It can be literally any type/

**Comment by Swoorup** [comment]
> Why `"Spline" | "Candles" | string;` instead of `string`? It can be literally any type/

Discoverability, and autocompletion of the built-in types. Even though `"Spline" | "Candles" | string;` is the same as `string`, ides can give you hints on what the possible types are. 

Btw I have changed such that you have `BuiltInCandleOverlay` which restricts both the type and the shape of the data later.

**Comment by Swoorup** [comment]
image

**Comment by C451** [comment]
Ok, will look into

**Pull request merged**
